### PR TITLE
Fix all bugs for favorite and cookbook buttons

### LINKED ISSUE #64: Favorites: be able to remove recipe from favorites page when its favorite button is clicked

### LINKED ISSUE #66: for cookbook toggle button, try splitting up the logic in the elsif statements where we change the value and add the class

### PR DESCRIPTION
**Pull request by aliroemhildt**
#### What's this PR do?
- correctly displays favorite button status on each card
- adds functionality to favorite button on individual recipe view 
- allows user to remove recipe from favorites view when you unfavorite a recipe card

#### Where should the reviewer start?
scripts.js - displayRecipes, displayFavorites, displayCookbook, displaySelectedRecipe functions

#### How should this be manually tested?
- open site with `npm start` portal
- click around, add things to favorites and cookbook, and then remove them. The favorite/cookbook buttons should reflect the current status of that recipe (aka is it currently in the user's favorites or cookbook array?)

#### Any background context you want to provide?
n/a

#### What are the relevant tickets?
n/a

#### Screenshots (if appropriate)
n/a

#### Questions:
n/a

### CODE REVIEW

File: src/scripts.js [hunk 1]
```diff
@@ -55,20 +55,27 @@ homeButton.addEventListener('click', displayHomePage);
...
 cookbookPageButton.addEventListener('click', displayCookbook);
+singleViewFavoriteButton.addEventListener('click', favoriteFromSingleRecipeView);
 
 // FUNCTIONS
 function displayFavorites() {
   hide([favoritePageButton]);
   show([homeButton, filterSection, recipeSection, mainView]);
   displayRecipes(currentUser.favorites);
   recipeCards = document.querySelectorAll('.recipe-card-js');
+  console.log(recipeCards);
```
Comment (anewb87) [inline src/scripts.js:66]: will delete

File: src/scripts.js [hunk 2]
```diff
@@ -55,20 +55,27 @@ homeButton.addEventListener('click', displayHomePage);
...
   recipeCards.forEach(card => {
-    const button = card.childNodes[3].childNodes[1]
-    button.value = 'favorited';
-    button.classList.add('favorited-state');
+    card.addEventListener('click', removeFromPage);
   });
 }
 
+function removeFromPage() {
```
Comment (anewb87) [inline src/scripts.js:72]: quick & slick!

File: src/scripts.js [hunk 3]
```diff
@@ -55,20 +55,27 @@ homeButton.addEventListener('click', displayHomePage);
...
+  // if (currentUser.favorites.includes(e.target.closest('section').id.slice(2))) {
```
Comment (anewb87) [inline src/scripts.js:73]: will delete- started going down this path but realized there was a much simpler way to accomplish this

File: src/scripts.js [hunk 4]
```diff
@@ -95,22 +102,45 @@ function deselectFavoriteButton(e) {
...
+};
+
 function displayCookbook() {
   hide([addToCookbookButton, selectedRecipeView]);
   show([homeButton, filterSection, mainView, recipeSection, favoritePageButton, addToCookbookButton]);
   displayRecipes(currentUser.recipesToCook);
-  recipeCards = document.querySelectorAll('.recipe-card-js');
-  currentUser.recipesToCook.forEach(recipe => {
-    let id = recipe.id
+  // recipeCards = document.querySelectorAll('.recipe-card-js');
```
Comment (anewb87) [inline src/scripts.js:121]: more to delete

File: src/scripts.js [hunk 5]
```diff
@@ -178,16 +208,23 @@ function displayRecipes(recipes) {
...
-      //   // e.target.classList.add('favorited-state');
-      // } else {
-      //   deselectFavoriteButton();
-      // }
   });
+
   createCardEventListeners();
   createButtonEventListeners();
+
+  recipeCards = document.querySelectorAll('.recipe-card-js');
```
Comment (anewb87) [inline src/scripts.js:216]: logic that styles the cards correctly-> are they already selected/not and apply appropriate styling and value

File: src/scripts.js [hunk 6]
```diff
@@ -254,6 +282,14 @@ function displaySelectedRecipe(e) {
       addToCookbookButton.innerText = 'add to cookbook';
     }
 
+    if (currentUser.favorites.includes(selectedRecipe)) {
```
Comment (anewb87) [inline src/scripts.js:285]: We are aware that we have similar logic peppered in a couple places. They're not exactly the same. At this point, with little time left, we've chosen to keep it as-is since it's functional. Praying we'll have time to figure out how to make this logic more dynamic and possibly put in a helper function that will actually work. This will take some time that we don't currently have at this moment. That's the goal.

**Review by anewb87 — APPROVED** [review]
This was more complex than it first appeared. We've got similar logic in a couple places so if/when we get the chance to refactor, the plan is to head back into it and see if we can't create a dynamic helper function that will clean it up.

**Review by kammon10 — APPROVED** [review]
